//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Loan
    {
        public int LoanId { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime CheckOutDate { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ReturnDate { get; set; }

        
        // public decimal FinePrice { get; set; }

        private decimal? _FinePrice;
        public decimal? FinePrice

        {
            get
            {
                if (DateTime.Now > ReturnDate)
                {
                    this._FinePrice = ((DateTime.Now - ReturnDate).Days) * 0.50M;
                }
                else
                {
                    this._FinePrice = 0M;
                }

                return this._FinePrice;
            }




            set
            {

                this._FinePrice = value;

            }

           
        }







        public Nullable<int> MemberId { get; set; }
        public Nullable<int> ISBN { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Member Member { get; set; }
    }
}
